spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
resend.api.key=${RESEND_API_KEY}
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=${PORT:8082}

app.admin.passcode=pro
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=adm22004021@rmlau.ac.in
brevo.sender.name=Understory
# Email Configuration - Gmail SMTP
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_SMTP_LOGIN}
spring.mail.password=${BREVO_SMTP_KEY}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true


# OTP Configuration
otp.length=6
otp.expiry.minutes=10
otp.resend.cooldown.seconds=60
otp.max.attempts=5

# Email configuration
email.from=${MAIL_FROM}
email.from.name=Understory Shop
